//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string DateAdded { get; set; }
        public bool IsMain { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PublicId { get; set; }
    
        public virtual User User { get; set; }
    }
}
